### ISSUE TITLE
在底部刷新了之后，回到顶部，就参差不齐了，空白 item交换等。

### ISSUE THREAD

**Issue by briskemen** [unicool/MixedGridLayoutManager#2]
博主在使用过程中，有没有遇到以上问题啊。

**Comment by unicool** [comment]
你是调用了`notifyDataSetChanged()`吧, 这会把内部缓存的`spanIndex`数组清空, `onLayoutChildren`时会重新计算, 建议使用``: notifyItemChanged(int), notifyItemInserted(int), notifyItemRemoved(int), notifyItemRangeChanged(int, int), notifyItemRangeInserted(int, int), notifyItemRangeRemoved(int, int)
